version: "3.7"
services:
  worldapi:
    image: jamesdbloom/mockserver:mockserver-5.7.0
    expose:
      - 1080
    ports:
      - 1080:1080
    volumes:
      - ./src/test/resources/test/ssl/truststore:/ssl
    entrypoint: /opt/mockserver/run_mockserver.sh -serverPort 1080 -logLevel INFO -jvmOptions "-Dmockserver.javaKeyStoreFilePath='/ssl/jsquad.jks' -Dmockserver.javaKeyStorePassword='test1234' -Dmockserver.javaKeyStoreType='jks'"
  openbankdb:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'openbank'
      MYSQL_USER: openbank_user
      MYSQL_PASSWORD: ${OPENBANK_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    expose:
      - 3306
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=${ROOT_PASSWORD}", "-e", "'SHOW DATABASES;'"]
      timeout: 5s
      retries: 10
  securitydb:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'security'
      MYSQL_USER: security_user
      MYSQL_PASSWORD: ${SECURITY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    expose:
      - 3306
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=${ROOT_PASSWORD}", "-e", "'SHOW DATABASES;'"]
      timeout: 5s
      retries: 5
  flyway:
    image: flyway/flyway:6.0.6
    command: -url=jdbc:mysql://securitydb -schemas=security -user=root -password=${ROOT_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./security/sql:/flyway/sql
    depends_on:
      - securitydb
  openbank:
    image: openbank
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MASTER_SECRET: "${MASTER_KEY}"
      CONFIG_FILE_LOCATIONS: "classpath:application.properties,classpath:configuration_local.yaml,classpath:activemq.properties,classpath:openbank_jpa.yaml,classpath:security_jpa.yaml"
    ports:
      - 8443:8443
      - 9990:9990
    depends_on:
      - openbankdb
      - securitydb
      - worldapi
    restart: on-failure